# Docker Compose file
# nodejsdevtinder/docker-compose.yml

version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://manoj98achar:2VJBuTqAPsdTZS9t@cluster0.iyss4mk.mongodb.net/devTinder
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - devtinder-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - devtinder-network
    restart: unless-stopped

networks:
  devtinder-network:
    driver: bridge