# Docker Compose file
# nodejsdevtinder/docker-compose.yml

version: '3.8'

services:
  mongodb:
    image: mongo:7-jammy
    container_name: devtinder-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: devTinder
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - devtinder-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://admin:password123@mongodb:27017/devTinder?authSource=admin
      - PORT=7777
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - devtinder-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - devtinder-network
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  devtinder-network:
    driver: bridge